name: Publish Docker image

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Gitlab Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USER_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.gitlab.com/jeyamohan/docker/wordpress
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
